### Sign up a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "asd4@asd.com",
    "password": "asdfasdf"
}

### Sign in a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "asd4@asd.com",
    "password": "asdfasdf"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=asd3@asd.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/1

### Update a user with a given ID
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "asdasd@asd.com"
}